services:
  - type: web
    name: skillbridge-backend
    runtime: node
    repo: https://github.com/santho1421/skill-bridge
    plan: free
    region: singapore
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
      - key: JWT_SECRET
        generateValue: true
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: skillbridge
      - key: FRONTEND_URL
        sync: false
